import type { Metadata } from 'next';
import { Geist, Geist_Mono, Playwrite_AU_SA } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/ui/Navigation/Navigation';

const geistSPlay = Playwrite_AU_SA({
  variable: '--x',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable} ${geistSPlay.variable} `}>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
